server:
  port: 8082
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka


